# ===============================================
# Script generated by Dev: THNAM | 0942433452
# Auto-run with Administrator privileges
# ===============================================
if (!([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) {
    Start-Process powershell.exe "-NoProfile -ExecutionPolicy Bypass -File "$PSCommandPath"" -Verb RunAs
    exit
}
$ErrorActionPreference = "SilentlyContinue"

# Delete Key: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Chromium
if (Test-Path "HKLM:\SOFTWARE\Policies\Chromium") { Remove-Item -Path "HKLM:\SOFTWARE\Policies\Chromium" -Recurse -Force }
# Create Key: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Chromium
New-Item -Path "HKLM:\SOFTWARE\Policies\Chromium" -Force | Out-Null
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "GeminiSettings" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "GenAILocalFoundationalModelSettings" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "AutofillPredictionSettings" -Value 0x00000002 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "HelpMeWriteSettings" -Value 0x00000002 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "AIModeSettings" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "UrlKeyedAnonymizedDataCollectionEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "SearchSuggestEnabled" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "AutofillAddressEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "AutofillCreditCardEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "PasswordManagerEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "ImportAutofillFormData" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "PaymentMethodQueryEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "BackgroundModeEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "PrivacySandboxAdTopicsEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "PrivacySandboxAdMeasurementEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "PrivacySandboxSiteEnabledAdsEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "PrivacySandboxPromptEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "SpellcheckEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "ExtensionManifestV2Availability" -Value 0x00000002	;End of support on Chrome 139 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "SafeBrowsingExtendedReportingEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "DnsOverHttpsMode" -Value 'automatic'
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "DnsOverHttpsTemplates" -Value 'https://cloudflare-dns.com/dns-query{?dns}'
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "ShowFullUrlsInAddressBar" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "DefaultGeolocationSetting" -Value 0x00000002 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "DefaultNotificationsSetting" -Value 0x00000002 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "DefaultSensorsSetting" -Value 0x00000002 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "BlockThirdPartyCookies" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "SafeBrowsingProtectionLevel" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "PasswordLeakDetectionEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "HighEfficiencyModeEnabled" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "MemorySaverModeSavings" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "NetworkPredictionOptions" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "HardwareAccelerationModeEnabled" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "WebRtcIPHandling" -Value 'disable_non_proxied_udp'
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "RelatedWebsiteSetsEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "HttpsUpgradesEnabled" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "ShoppingListEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "SafeBrowsingSurveysEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "SafeBrowsingDeepScanningEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "AlternateErrorPagesEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "DefaultBrowserSettingEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "SideSearchEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Chromium" -Name "UserFeedbackAllowed" -Value 0x00000000 -Type DWord
# Create Key: HKEY_LOCAL_MACHINE\Software\Policies\Chromium\ExtensionInstallForcelist
New-Item -Path "HKLM:\Software\Policies\Chromium\ExtensionInstallForcelist" -Force | Out-Null
Set-ItemProperty -Path "HKLM:\Software\Policies\Chromium\ExtensionInstallForcelist" -Name "1" -Value 'jaadjnlkjnhohljficgoddcjmndjfdmi"  ; Blank New Tab Page'

# Restart Explorer
Start-Process 'explorer.exe'
Start-Sleep -Seconds 10
