# ===============================================
# Script generated by Dev: THNAM | 0942433452
# Auto-run with Administrator privileges
# ===============================================
if (!([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) {
    Start-Process powershell.exe "-NoProfile -ExecutionPolicy Bypass -File "$PSCommandPath"" -Verb RunAs
    exit
}
$ErrorActionPreference = "SilentlyContinue"

# Delete Key: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\CocCoc
if (Test-Path "HKLM:\SOFTWARE\Policies\CocCoc") { Remove-Item -Path "HKLM:\SOFTWARE\Policies\CocCoc" -Recurse -Force }
# Delete Key: HKEY_CURRENT_USER\SOFTWARE\Policies\CocCoc
if (Test-Path "HKCU:\SOFTWARE\Policies\CocCoc") { Remove-Item -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Recurse -Force }
# Create Key: HKEY_CURRENT_USER\SOFTWARE\Policies\CocCoc
New-Item -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Force | Out-Null
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "GeminiSettings" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "GenAILocalFoundationalModelSettings" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "AutofillPredictionSettings" -Value 0x00000002 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "HelpMeWriteSettings" -Value 0x00000002 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "AIModeSettings" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "CreateThemesSettings" -Value 0x00000002 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "HistorySearchSettings" -Value 0x00000002 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "TabCompareSettings" -Value 0x00000002 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "DevToolsGenAiSettings" -Value 0x00000002 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "AccessCodeCastEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "AccessibilityImageLabelsEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "AlternateErrorPagesEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "PasswordDismissCompromisedAlertEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "PasswordProtectionWarningTrigger" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "QRCodeGeneratorEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "RemoteDebuggingAllowed" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "RoamingProfileSupportEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "SafeBrowsingDeepScanningEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "SafeBrowsingProxiedRealTimeChecksAllowed" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "SafeBrowsingSurveysEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "ShoppingListEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "SideSearchEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "SigninInterceptionEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "UserFeedbackAllowed" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "FeedbackSurveysEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "UrlKeyedAnonymizedDataCollectionEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "SearchSuggestEnabled" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "AutofillAddressEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "AutofillCreditCardEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "PasswordManagerEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "PaymentMethodQueryEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "BackgroundModeEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "PrivacySandboxPromptEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "SpellcheckEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "SafeBrowsingExtendedReportingEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "ShowFullUrlsInAddressBar" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "DefaultGeolocationSetting" -Value 0x00000002 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "DefaultNotificationsSetting" -Value 0x00000002 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "DefaultSensorsSetting" -Value 0x00000002 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "BlockThirdPartyCookies" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "SafeBrowsingProtectionLevel" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "PasswordLeakDetectionEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "HighEfficiencyModeEnabled" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "MemorySaverModeSavings" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "NetworkPredictionOptions" -Value 0x00000003 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "HardwareAccelerationModeEnabled" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "WebRtcIPHandling" -Value 'disable_non_proxied_udp'
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "HttpsUpgradesEnabled" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "HttpsOnlyMode" -Value 'force_enabled'
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "ShoppingListEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "SafeBrowsingSurveysEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "SafeBrowsingDeepScanningEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "AlternateErrorPagesEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "DefaultBrowserSettingEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "SideSearchEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "SpellCheckServiceEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "DnsOverHttpsMode" -Value 'secure'
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc" -Name "DnsOverHttpsTemplates" -Value 'https://iabucttpma.cloudflare-gateway.com/dns-query{?dns}'
# Create Key: HKEY_CURRENT_USER\SOFTWARE\Policies\CocCoc\URLBlocklist
New-Item -Path "HKCU:\SOFTWARE\Policies\CocCoc\URLBlocklist" -Force | Out-Null
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc\URLBlocklist" -Name "1" -Value 'update.coccoc.com'
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc\URLBlocklist" -Name "2" -Value 'afl.coccoc.com'
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc\URLBlocklist" -Name "3" -Value 'afdk.coccoc.com'
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc\URLBlocklist" -Name "4" -Value 'metrics.coccoc.com'
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc\URLBlocklist" -Name "5" -Value 'qccoccocmedia.vn'
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc\URLBlocklist" -Name "6" -Value 'coccoc.telemetry.eyeo.com'
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc\URLBlocklist" -Name "7" -Value 'new-tab.coccoc.com'
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc\URLBlocklist" -Name "8" -Value 'qc-static.coccoc.com'
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc\URLBlocklist" -Name "9" -Value 'qc.coccoc.com'
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc\URLBlocklist" -Name "10" -Value 's.qc.coccoc.com'
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc\URLBlocklist" -Name "11" -Value 'video.comedia.coccoc.com'
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc\URLBlocklist" -Name "12" -Value 'display.qc.coccoc.com'
Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\CocCoc\URLBlocklist" -Name "13" -Value '.coccoc.com'

# Restart Explorer
Start-Process 'explorer.exe'
Start-Sleep -Seconds 10
