# ===============================================
# Script generated by Dev: THNAM | 0942433452
# Auto-run with Administrator privileges
# ===============================================
if (!([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) {
    Start-Process powershell.exe "-NoProfile -ExecutionPolicy Bypass -File "$PSCommandPath"" -Verb RunAs
    exit
}
$ErrorActionPreference = "SilentlyContinue"

# Delete Key: HKEY_LOCAL_MACHINE\Software\Policies\BraveSoftware\Brave
if (Test-Path "HKLM:\Software\Policies\BraveSoftware\Brave") { Remove-Item -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Recurse -Force }
# Create Key: HKEY_LOCAL_MACHINE\Software\Policies\BraveSoftware\Brave
New-Item -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Force | Out-Null
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "BraveRewardsDisabled" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "BraveWalletDisabled" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "BraveVPNDisabled" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "BraveAIChatEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "TorDisabled" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "BraveNewsDisabled" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "BraveTalkDisabled" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "BraveSpeedreaderDisabled" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "BraveWaybackMachineDisabled" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "ShoppingListEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "SafeBrowsingSurveysEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "SafeBrowsingDeepScanningEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "AlternateErrorPagesEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "DefaultBrowserSettingEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "UrlKeyedAnonymizedDataCollectionEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "SearchSuggestEnabled" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "AutofillAddressEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "AutofillCreditCardEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "PasswordManagerEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "PasswordSharingEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "PasswordLeakDetectionEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "PaymentMethodQueryEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "BackgroundModeEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "PrivacySandboxAdTopicsEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "PrivacySandboxAdMeasurementEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "PrivacySandboxSiteEnabledAdsEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "PrivacySandboxPromptEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "SpellcheckEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "ExtensionManifestV2Availability" -Value 0x00000002 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "SafeBrowsingExtendedReportingEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "DnsOverHttpsMode" -Value 'automatic'
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "DnsOverHttpsTemplates" -Value 'https://cloudflare-dns.com/dns-query{?dns}'
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "ShowFullUrlsInAddressBar" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "DefaultGeolocationSetting" -Value 0x00000002 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "DefaultNotificationsSetting" -Value 0x00000002 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "BlockThirdPartyCookies" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "SafeBrowsingProtectionLevel" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "HighEfficiencyModeEnabled" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "MemorySaverModeSavings" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "NetworkPredictionOptions" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "HardwareAccelerationModeEnabled" -Value 0x00000001 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "WebRtcIPHandling" -Value 'disable_non_proxied_udp'
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "RelatedWebsiteSetsEnabled" -Value 0x00000000 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "AutofillPredictionSettings" -Value 0x00000002 -Type DWord
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave" -Name "HttpsUpgradesEnabled" -Value 0x00000001 -Type DWord
# Create Key: HKEY_LOCAL_MACHINE\Software\Policies\BraveSoftware\Brave\ExtensionInstallForcelist
New-Item -Path "HKLM:\Software\Policies\BraveSoftware\Brave\ExtensionInstallForcelist" -Force | Out-Null
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave\ExtensionInstallForcelist" -Name "1" -Value 'jaadjnlkjnhohljficgoddcjmndjfdmi"  ; Blank New Tab Page'
Set-ItemProperty -Path "HKLM:\Software\Policies\BraveSoftware\Brave\ExtensionInstallForcelist" -Name "2" -Value 'nomnklagbgmgghhjidfhnoelnjfndfpd"  ; Canvas Blocker - Fingerprint Protect'

# Restart Explorer
Start-Process 'explorer.exe'
Start-Sleep -Seconds 10
